server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: ruoyi-example-demo
  profiles:
    active: dev

logging:
  level:
    com.ruoyi: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"